### ISSUE TITLE
Smarter rendering of popups

### ISSUE THREAD

**Issue by wokste** [wokste/LotUS-Roguelike#24]
Currently, every frame, all popups are drawn, even if this is not needed. Probably requires some magic with dirty flags. This is a bug that needs to be addressed.

Suggested solution: Add a return value to Widget.Render(). Based on this, decide whether the popups need to be redrawn.

**Comment by tstavrianos** [comment]
You might get an additional performance gain if you include a visible property to widgets and use it to immediately exit the render function if they are hidden.

**Comment by wokste** [comment]
I am appearantly not explaining my issues clear enough. Widgets have a render function and it will render itself if a) the widget decides it is dirty or b) I will pass a forceUpdate flag to the widget. This flag is true when I do a resize, etc.

For non-popup widgets this worked fine as they don't overlap. If I don't render, it still has the content of the previous frame in memory and it all works fine.

For overlapping widgets, the problem is that I don't know if any widget has been updated. As a quick-fix I lazily set forceUpdate to true and made this ticket as a reminder. Maybe I should take some time to fix this issue.
