### ISSUE TITLE
Optimize rendering

### ISSUE THREAD

**Issue by wokste** [wokste/LotUS-Roguelike#3]
Currently: rendering is relatively slow, because of the OpenGL 1 functions SFML uses. Optimize this, for example using shaders, etc.

**Comment by wokste** [comment]
An example can be found here:
https://bitbucket.org/libtcod/libtcod/src/46f1f32fcec74a2c7c9b947553730cd4c580ff6b/src/sys_opengl_c.c?at=default&fileviewer=file-view-default

**Comment by tstavrianos** [comment]
This might be of help (if you want an alternative to GLSL that might be relatively quick):
https://github.com/thebracket/rltk/blob/master/rltk/virtual_terminal.cpp

**Comment by wokste** [comment]
That looks like a good solution. I saw in a test of libtcod that while the OpenGL implementation was slower than the GLSL one, they were both in the order of thousands of FPS. So, it seems that it should be good enough. Maybe this helps me to give the motivation to tackle the problem once and for all.
